name: Keep Render Alive
on: 
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Site
        run: curl -s https://littlemathstar.onrender.com
